#!/bin/bash

# Create a simple 16x16 blue PNG (base64 encoded minimal PNG)
echo "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAMklEQVR42mNgGAWjYBSMgqEBGBkZ/zMyMv5nYGD4z0AaYGJi+s/ExPSfEUI
MKRgFAwYAAMo6BgFKpHioAAAAAElFTkSuQmCC" | base64 -d > icon16.png

# Create a simple 48x48 blue PNG
echo "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAO0lEQVR42u3OMQ0AAAgDILV/54cBBgKSrkknAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQGBXwHv/wGgCRFQkAAAAABJRU5ErkJggg==" | base64 -d > icon48.png

# Create a simple 128x128 blue PNG
echo "iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAAP0lEQVR42u3QMQ0AAAgDILV/50eCByQSiZ6T7hEREREREREREREREREREREREREREREREREREREREREREZF/MfwEAAHmZQEBgFsAAAAASUVORK5CYII=" | base64 -d > icon128.png

echo "Basic icon files created"
